// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sweeprr.API.Data;

#nullable disable

namespace Sweeprr.API.Data.Migrations
{
    [DbContext(typeof(SweeprrDbContext))]
    [Migration("20260613093628_AddBackupSetting")]
    partial class AddBackupSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Sweeprr.API.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_ActivityLogs_Category");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_ActivityLogs_Timestamp");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Sweeprr.API.Models.BackupSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("S3AccessKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3Bucket")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3SecretKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleCron")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupSettings", t =>
                        {
                            t.HasCheckConstraint("CK_BackupSetting_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("Sweeprr.API.Models.Exclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaServerItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaServerItemId")
                        .HasDatabaseName("IX_Exclusions_MediaServerItemId");

                    b.HasIndex("RuleGroupId");

                    b.ToTable("Exclusions");
                });

            modelBuilder.Entity("Sweeprr.API.Models.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDirectJellyfinDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultCron")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GlobalDryRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JellyfinSessionAlertsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwtSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeavingSoonCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LeavingSoonSyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LibraryPercentCap")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxGbPerRun")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxItemsPerRun")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OverBroadMatchPct")
                        .HasColumnType("REAL");

                    b.Property<double>("PessimisticSizeGb")
                        .HasColumnType("REAL");

                    b.Property<int>("PlaybackHistoryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterBackupDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PosterOverlaysEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreSweepBroadcastEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicBaseUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", t =>
                        {
                            t.HasCheckConstraint("CK_GlobalSettings_SingleRow", "Id = 1");
                        });
                });

            modelBuilder.Entity("Sweeprr.API.Models.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggerOnConnectionError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggerOnFailsafe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggerOnPendingItems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggerOnSweepComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrlEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Sweeprr.API.Models.PlaybackActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWatched")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaServerItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastWatched")
                        .HasDatabaseName("IX_PlaybackActivities_LastWatched");

                    b.HasIndex("MediaServerItemId", "UserId")
                        .HasDatabaseName("IX_PlaybackActivities_MediaServerItemId_UserId");

                    b.ToTable("PlaybackActivities");
                });

            modelBuilder.Entity("Sweeprr.API.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comparator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LogicalOperator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuleGroupId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Sweeprr.API.Models.RuleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddImportExclusion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronOverride")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetQualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetQualityProfileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RuleGroups");
                });

            modelBuilder.Entity("Sweeprr.API.Models.ServerConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastConnectionOk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServerConnections");
                });

            modelBuilder.Entity("Sweeprr.API.Models.SweepItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArrInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FlaggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedRuleSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaServerItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SweptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TvdbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SweepItems_Status");

                    b.HasIndex("RuleGroupId", "MediaServerItemId")
                        .HasDatabaseName("IX_SweepItems_GroupItem");

                    b.HasIndex("RuleGroupId", "Status")
                        .HasDatabaseName("IX_SweepItems_GroupStatus");

                    b.ToTable("SweepItems");
                });

            modelBuilder.Entity("Sweeprr.API.Models.SweeprrApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaskedKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashedKey")
                        .IsUnique()
                        .HasDatabaseName("IX_SweeprrApiKeys_HashedKey");

                    b.ToTable("SweeprrApiKeys");
                });

            modelBuilder.Entity("Sweeprr.API.Models.TagExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleGroupId");

                    b.HasIndex("ServerConnectionId")
                        .HasDatabaseName("IX_TagExclusions_ServerConnectionId");

                    b.ToTable("TagExclusions");
                });

            modelBuilder.Entity("Sweeprr.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sweeprr.API.Models.Exclusion", b =>
                {
                    b.HasOne("Sweeprr.API.Models.RuleGroup", "RuleGroup")
                        .WithMany()
                        .HasForeignKey("RuleGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RuleGroup");
                });

            modelBuilder.Entity("Sweeprr.API.Models.Rule", b =>
                {
                    b.HasOne("Sweeprr.API.Models.RuleGroup", "RuleGroup")
                        .WithMany("Rules")
                        .HasForeignKey("RuleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleGroup");
                });

            modelBuilder.Entity("Sweeprr.API.Models.SweepItem", b =>
                {
                    b.HasOne("Sweeprr.API.Models.RuleGroup", "RuleGroup")
                        .WithMany("SweepItems")
                        .HasForeignKey("RuleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleGroup");
                });

            modelBuilder.Entity("Sweeprr.API.Models.TagExclusion", b =>
                {
                    b.HasOne("Sweeprr.API.Models.RuleGroup", "RuleGroup")
                        .WithMany()
                        .HasForeignKey("RuleGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sweeprr.API.Models.ServerConnection", "ServerConnection")
                        .WithMany()
                        .HasForeignKey("ServerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleGroup");

                    b.Navigation("ServerConnection");
                });

            modelBuilder.Entity("Sweeprr.API.Models.RuleGroup", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("SweepItems");
                });
#pragma warning restore 612, 618
        }
    }
}
